### ISSUE TITLE
Gerber or BOM not updated for 0.6

### ISSUE THREAD

**Issue by dssoftx** [badgineer/CCC_ESC#19]
When trying to get a MP2-ESC V0.6 assembled on JLCPCB using the provided BOM, CPL and Gerber i get such an error.
![Capture](https://github.com/badgineer/MP2-ESC/assets/69913272/f45d0ddd-1cdb-4b1b-ab8a-6c9d93d80cf1)

**Comment by dssoftx** [comment]
Im stupid, these are pads for caps

**Comment by badgineer** [comment]
Hi there. 
yes, these are parts not populated on purpose. 
so are the snubber caps and resistors. 
By the way, 0.6 is not tested, at least not to my knowledge. so if you find problems (or want to report success) get in touch. 
There's an endless sphere thread you can post in.
Br, 
badgineer
