### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by jsam** [badgineer/CCC_ESC#5]
Hey,

Just found this really cool project and wanted to drop in and say thank you for open sourcing it!

Do you think its possible to improve the docs a bit for not-so-experienced hardware people. 

Few things I see it would help a lot is maybe:
  1) Adding a `bom` file and instructions on ordering it from JLCPCB
  2) Assembly instructions
  3) Instruction on building/hooking up all the different modules
  4) Contribution guidelines / roadmap

Thank you!
Sam.

**Comment by badgineer** [comment]
Hi.
Thanks for the interest

I thiught there is a bom, i will regenerate it when i get a chance (very
busy atm).
The same for module list - we have some tested some not yet tested we can
recomment.

Aslo, more info there will be on the ES thread and hopefully in a
half-useful readme.

https://endless-sphere.com/forums/viewtopic.php?t=117045


We are in the testing phae cureently btw, slowly adding improvements
resulted from testing to the design.

Also heavily working on software in paralell (not me, other people more
softwarw savvy )

If yiu have improvement ideeas, feel free to post to es thread :)


Br,

**Comment by badgineer** [comment]
Hi.
Started taking documentation more seriously. See Readme :)
Haven't added guides for assembly here, hope to add some in the ES thread I linked to. (when I finally get the time to assemble my v01 prototype)

Best Regards!

**Comment by badgineer** [comment]
Hi.
So documentation is still not perfect - and it will probably never be. 
But I think its good enough that I can close this :)

Best Regards.

**Comment by jsam** [comment]
Thanks a lot!
